import { Link, useSearchParams } from "react-router-dom";
import { FileImage, Plus, Trash2, Eye, Search, X } from "lucide-react";
import { getDesigns, saveDesigns } from "../store";
import { useState } from "react";

export default function DesignsPage(){
 const [designs,setDesigns]=useState(getDesigns()); const [q,setQ]=useState(""); const [params,setParams]=useSearchParams();
 const selected=params.get("case"); const selectedCase=designs.find(d=>d.id===selected);
 const filtered=designs.filter(d=>`${d.patientName} ${d.treatment}`.toLowerCase().includes(q.toLowerCase()));
 const remove=(id:string)=>{if(!confirm("Delete this smile design?"))return;const next=designs.filter(d=>d.id!==id);saveDesigns(next);setDesigns(next);if(selected===id)setParams({})};
 return <div className="px-5 py-8 md:px-10"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><h1 className="text-2xl font-bold">Smile Designs</h1><p className="mt-1 text-sm text-slate-500">Create, review and manage treatment simulations.</p></div><Link to="/new-design" className="inline-flex items-center justify-center gap-2 rounded-xl bg-teal-900 px-4 py-3 text-sm font-semibold text-white"><Plus size={17}/> New Design</Link></div>
 <div className="mt-6 flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-3 shadow-sm"><Search size={18} className="text-slate-400"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search by patient or treatment..." className="w-full outline-none text-sm"/></div>
 <div className="mt-5 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">{filtered.length===0?<div className="p-12 text-center"><FileImage className="mx-auto text-slate-300" size={38}/><h3 className="mt-4 font-semibold">No designs found</h3><p className="mt-1 text-sm text-slate-500">Create a new smile design to see it here.</p></div>:<div className="divide-y divide-slate-100">{filtered.map(d=><div key={d.id} className="flex flex-col gap-4 p-5 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-4">{d.imageData?<img src={d.imageData} className="h-16 w-24 rounded-lg object-cover"/>:<div className="flex h-16 w-24 items-center justify-center rounded-lg bg-teal-50 text-teal-700"><FileImage/></div>}<div><h3 className="font-semibold">{d.patientName}</h3><p className="text-sm capitalize text-slate-500">{d.treatment} · {d.intensity}%</p><p className="text-xs text-slate-400">{new Date(d.createdAt).toLocaleString()}</p></div></div><div className="flex gap-2"><button onClick={()=>setParams({case:d.id})} className="rounded-lg border border-slate-200 p-2 text-slate-600 hover:bg-slate-50" title="View"><Eye size={18}/></button><button onClick={()=>remove(d.id)} className="rounded-lg border border-red-100 p-2 text-red-600 hover:bg-red-50" title="Delete"><Trash2 size={18}/></button></div></div>)}</div>}</div>
 {selectedCase&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/30 p-4"><div className="max-h-[92vh] w-full max-w-4xl overflow-auto rounded-2xl bg-white p-6 shadow-xl"><div className="flex items-start justify-between"><div><p className="text-xs uppercase tracking-wider text-teal-700">Smile Design</p><h2 className="mt-1 text-2xl font-bold">{selectedCase.patientName}</h2><p className="mt-1 text-sm capitalize text-slate-500">{selectedCase.treatment} · {selectedCase.intensity}% · {selectedCase.status}</p></div><button onClick={()=>setParams({})} className="rounded-lg p-2 hover:bg-slate-100"><X/></button></div><div className="mt-6 grid gap-5 md:grid-cols-2">{[["Original",selectedCase.imageData], ["Simulated",selectedCase.resultData]].map(([label,src])=><div key={String(label)}><p className="mb-2 text-xs font-semibold uppercase tracking-wider text-slate-500">{label}</p><div className="flex min-h-[260px] items-center justify-center overflow-hidden rounded-xl border bg-slate-50">{src?<img src={src as string} className="max-h-[520px] w-full object-contain"/>:<p className="text-sm text-slate-400">Image unavailable</p>}</div></div>)}</div></div></div>}
 </div>;
}
