import { Search, Plus, UserRound, Pencil, Trash2, X } from "lucide-react";
import { useState } from "react";
import { getPatients, savePatients, makeId } from "../store";
import type { Patient } from "../types";

const empty={name:"",age:25,email:"",phone:"",notes:""};
export default function PatientsPage(){const [patients,setPatients]=useState(getPatients());const [q,setQ]=useState("");const [modal,setModal]=useState(false);const [editing,setEditing]=useState<Patient|null>(null);const [form,setForm]=useState(empty);
 const open=(p?:Patient)=>{setEditing(p??null);setForm(p?{name:p.name,age:p.age,email:p.email,phone:p.phone,notes:p.notes}:empty);setModal(true)};
 const submit=(e:React.FormEvent)=>{e.preventDefault();if(!form.name.trim())return;let next:Patient[];if(editing)next=patients.map(p=>p.id===editing.id?{...editing,...form,age:Number(form.age)}:p);else next=[{...form,age:Number(form.age),id:makeId("p"),createdAt:new Date().toISOString()},...patients];savePatients(next);setPatients(next);setModal(false)};
 const remove=(id:string)=>{if(!confirm("Delete this patient?"))return;const next=patients.filter(p=>p.id!==id);savePatients(next);setPatients(next)};
 const filtered=patients.filter(p=>`${p.name} ${p.email} ${p.phone}`.toLowerCase().includes(q.toLowerCase()));
 return <div className="px-5 py-8 md:px-10"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><h1 className="text-2xl font-bold">Patients</h1><p className="mt-1 text-sm text-slate-500">Maintain patient records for your smile design workflow.</p></div><button onClick={()=>open()} className="inline-flex items-center justify-center gap-2 rounded-xl bg-teal-900 px-4 py-3 text-sm font-semibold text-white"><Plus size={17}/> Add Patient</button></div>
 <div className="mt-6 flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-3 shadow-sm"><Search size={18} className="text-slate-400"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search patients..." className="w-full outline-none text-sm"/></div>
 <div className="mt-5 grid gap-4 lg:grid-cols-2">{filtered.map(p=><div key={p.id} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex justify-between gap-3"><div className="flex gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-full bg-teal-50 text-teal-800"><UserRound size={20}/></div><div><h3 className="font-semibold">{p.name}</h3><p className="text-xs text-slate-500">Age {p.age}</p></div></div><div className="flex gap-1"><button onClick={()=>open(p)} className="p-2 text-slate-500 hover:text-teal-800"><Pencil size={17}/></button><button onClick={()=>remove(p.id)} className="p-2 text-red-500"><Trash2 size={17}/></button></div></div><div className="mt-4 grid gap-1 text-sm text-slate-600"><p>{p.email||"No email"}</p><p>{p.phone||"No phone"}</p></div>{p.notes&&<p className="mt-3 rounded-lg bg-slate-50 p-3 text-xs text-slate-500">{p.notes}</p>}</div>)}</div>
 {filtered.length===0&&<div className="mt-5 rounded-2xl border border-dashed p-12 text-center text-sm text-slate-500">No patients match your search.</div>}
 {modal&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/30 p-4"><form onSubmit={submit} className="w-full max-w-lg rounded-2xl bg-white p-6 shadow-xl"><div className="flex items-center justify-between"><h2 className="text-xl font-bold">{editing?"Edit Patient":"Add Patient"}</h2><button type="button" onClick={()=>setModal(false)}><X/></button></div><div className="mt-5 grid gap-4 sm:grid-cols-2">{[["name","Full name"],["age","Age"],["email","Email"],["phone","Phone"]].map(([key,label])=><label key={key} className="text-sm font-medium">{label}<input required={key==="name"} type={key==="age"?"number":"text"} value={(form as any)[key]} onChange={e=>setForm({...form,[key]:key==="age"?Number(e.target.value):e.target.value})} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 outline-none focus:border-teal-600"/></label>)}<label className="text-sm font-medium sm:col-span-2">Notes<textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} rows={3} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 outline-none focus:border-teal-600"/></label></div><button className="mt-5 w-full rounded-xl bg-teal-900 py-3 font-semibold text-white">Save Patient</button></form></div>}
 </div>;
}
