import { Download, FileText, BarChart3 } from "lucide-react";
import { getDesigns, getPatients } from "../store";
import { useMemo } from "react";
export default function ReportsPage(){const patients=getPatients();const designs=getDesigns();const counts=useMemo(()=>({whitening:designs.filter(d=>d.treatment==="whitening").length,alignment:designs.filter(d=>d.treatment==="alignment").length,veneers:designs.filter(d=>d.treatment==="veneers").length,combined:designs.filter(d=>d.treatment==="combined").length}),[designs]);
 const download=()=>{const rows=["Patient,Treatment,Intensity,Status,Created",...designs.map(d=>[d.patientName,d.treatment,d.intensity,d.status,new Date(d.createdAt).toLocaleString()].map(x=>`"${String(x).replaceAll('"','""')}"`).join(","))];const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([rows.join("\n")],{type:"text/csv"}));a.download="dentaform-report.csv";a.click();URL.revokeObjectURL(a.href)};
 return <div className="space-y-6 px-5 py-8 md:px-10"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><h1 className="text-2xl font-bold">Reports</h1><p className="mt-1 text-sm text-slate-500">A simple overview of your local smile design activity.</p></div><button onClick={download} className="inline-flex items-center justify-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm font-semibold"><Download size={17}/> Export CSV</button></div>
 <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{Object.entries(counts).map(([k,v])=><div className="rounded-2xl border bg-white p-5 shadow-sm" key={k}><p className="text-xs uppercase tracking-wider text-slate-500">{k}</p><p className="mt-2 text-3xl font-bold">{v}</p></div>)}</div>
 <div className="grid gap-6 lg:grid-cols-2"><div className="rounded-2xl border bg-white p-6 shadow-sm"><BarChart3 className="text-teal-800"/><h2 className="mt-4 font-bold">Case summary</h2><div className="mt-5 space-y-3">{[["Total patients",patients.length],["Total designs",designs.length],["Completed designs",designs.filter(d=>d.status==="Completed").length]].map(([l,v])=><div className="flex justify-between border-b py-2 text-sm" key={String(l)}><span className="text-slate-500">{l}</span><b>{v}</b></div>)}</div></div><div className="rounded-2xl border bg-white p-6 shadow-sm"><FileText className="text-teal-800"/><h2 className="mt-4 font-bold">Report export</h2><p className="mt-2 text-sm leading-6 text-slate-500">Export the current design list as a CSV file for review or sharing. This frontend report uses data stored locally in this browser.</p><button onClick={download} className="mt-5 rounded-xl bg-teal-900 px-4 py-3 text-sm font-semibold text-white">Download report</button></div></div></div>;
}
